# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Driver Nick Name'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver WeChat ID'),
        ),
    ]
